require("local/lspkind");
require("local/lsp");
require("local/pylsp");
-- require("local/pyright");
require("local/treesitter");
require("local/web-devicons");
require("local/gitsigns");
require("local/diffview");
require("local/lsp-trouble");
require("local/nvim-compe");
require("local/nvim_tree");
require("local/lsp_colors");
-- require("local/flow");
require("local/tsserver");
require("local/telescope");
