#!/bin/bash

source pkgs.sh
source in_up.sh

if [[ ! -d  ~/.nvim/bundle/vimproc ]]; then
    pr_info "Installing vimproc"
    git clone https://github.com/Shougo/vimproc.vim ~/.nvim/bundle/vimproc
    cd ~/.nvim/bundle/vimproc
    make
    cd -
fi

if [[ ! -d  ~/.nvim/bundle/neobundle.vim ]]; then
    pr_info "Installing neobundle."
    git clone git://github.com/Shougo/neobundle.vim ~/.nvim/bundle/neobundle.vim
fi

export THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ -f ~/.nvimrc ]]; then
    pr_info "Backuping up the existing ~/.nvimrc"
    mv --backup=numbered ~/.nvimrc ~/.nvimrc.bak
    pr_info "~/.nvimrc backups: \n$(ls ~/.nvimrc.bak*)"
fi

pr_info "Creating the new ~/.nvimrc"
export PKGS_NVIM_DIR="$(dirname $THIS_DIR/)/nvim"
echo "set runtimepath+=$PKGS_NVIM_DIR" > ~/.nvimrc
echo "source $PKGS_NVIM_DIR/.nvimrc" >> ~/.nvimrc

pr_info "Updating bundles..."
echo "y\ny\ny\n" | nvim -c 'NeoBundleInstall!<\CR>' -c 'q'
wait

pr_info "Updating Remote Plugins..."
nvim -c "UpdateRemotePlugins" -c "qa"
wait

source buildycm.sh

# pr_info "Building vimproc .so..."
# cd ~/.nvim/bundle/vimproc
# make
# cd -

pr_pass "Install complete"
