#!/bin/bash

source pkgs.sh

# Make sure we have an undos directory
mkdir -p ~/.nvim/undos

mkdir -p ~/.nvim/bundle
if [[ ! -d  ~/.nvim/bundle/neobundle.vim ]]; then
    pr_info "Installing neobundle."
    git clone git://github.com/Shougo/neobundle.vim ~/.nvim/bundle/neobundle.vim
fi

export THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ -f ~/.nvimrc ]]; then
    pr_info "Backuping up the existing ~/.nvimrc"
    mv --backup=numbered ~/.nvimrc ~/.nvimrc.bak
    pr_info "~/.nvimrc backups: \n$(ls ~/.nvimrc.bak*)"
fi

pr_info "Creating the new ~/.nvimrc"
export PKGS_NVIM_DIR="$(dirname $THIS_DIR/)/nvim"
echo "set runtimepath+=$PKGS_NVIM_DIR" > ~/.nvimrc
echo "source $PKGS_NVIM_DIR/.nvimrc" >> ~/.nvimrc

pr_info "Updating bundles..."
echo "y\ny\ny\n" | nvim +'NeoBundleInstall!<\CR>' +'q'
wait

source buildycm.sh

pr_info "Building vimproc .so..."
cd ~/.nvim/bundle/vimproc
make
cd -

pr_pass "Install complete"
