#!/bin/bash

source pkgs.sh
source nvimenv.sh
source in_up.sh

source buildycm.sh


pr_info "Updating bundles..."
echo "y\ny\ny\n" | nvim -c 'NeoBundleInstall!<\CR>' -c 'q'
wait

pr_info "Updating Remote Plugins..."
nvim -c 'UpdateRemotePlugins<\CR>' -c "qa"
wait
