#!/bin/bash

source pkgs.sh

# Make sure we have an undos directory
mkdir -p ~/.vim/undos

source buildycm.sh

# Link our UltiSnips up
ln -nsf ${THIS_DIR}/../nvim/UltiSnips ~/.nvim/

pr_info "Updating bundles..."
echo "y\ny\ny\n" | nvim +'NeoBundleCheck<\CR>' +'q'
wait
