return {
  -- {
  --   "folke/flash.nvim",
  --   enabled = false,
  -- },
  -- {
  --   "nvim-mini/mini.bufremove",
  --   enabled = false,
  -- },
  -- -- {
  -- --   "nvimdev/dashboard-nvim",
  -- --   enabled = false,
  -- -- },
  -- {
  --   "lukas-reineke/indent-blankline.nvim",
  --   enabled = false,
  -- },
  -- -- {
  -- --   "dstein64/vim-startuptime",
  -- --   enabled = false,
  -- -- },
}
