return {
  -- {
  --   "coder/claudecode.nvim",
  --   config = true,
  --   keys = {
  --     { "<leader>a", nil, desc = "AI/Claude Code" },
  --     { "<leader>ac", "<cmd>ClaudeCode<cr>", desc = "Toggle Claude" },
  --     { "<leader>as", "<cmd>ClaudeCodeSend<cr>", mode = "v", desc = "Send to Claude" },
  --     { "<leader>af", "<cmd>ClaudeCodeFocus<cr>", desc = "Focus Claude" },
  --     { "<leader>ar", "<cmd>ClaudeCode --resume<cr>", desc = "Resume Claude" },
  --     { "<leader>aC", "<cmd>ClaudeCode --continue<cr>", desc = "Continue Claude" },
  --
  --     {
  --       "<leader>as",
  --       "<cmd>ClaudeCodeTreeAdd<cr>",
  --       desc = "Add file to AI Ctx",
  --       ft = { "NvimTree", "neo-tree" },
  --     },
  --     { "<leader>ao", "<cmd>ClaudeCodeOpen<cr>", desc = "Open Claude" },
  --     { "<leader>ax", "<cmd>ClaudeCodeClose<cr>", desc = "Close Claude" },
  --
  --     -- diff management
  --     { "<leader>aa", "<cmd>claudecodediffaccept<cr>", desc = "accept diff" },
  --     { "<leader>ad", "<cmd>ClaudeCodeDiffDeny<cr>", desc = "Deny diff" },
  --   },
  --   opts = {
  --     -- Terminal options
  --     terminal = {
  --       split_side = "right",
  --       split_width_percentage = 0.5,
  --       provider = "snacks", -- or "native"
  --     },
  --     -- Diff options
  --     diff_opts = {
  --       auto_close_on_accept = true,
  --       vertical_split = true,
  --       open_in_current_tab = false,
  --     },
  --   },
  -- },
}
