return {
  "mason-org/mason.nvim",

  opts_extend = { "ensure_installed" },
  opts = {
    ensure_installed = {
      "bash-language-server",
      "codespell",
      "cueimports",
      "cuelsp",
      "delve",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "golangci-lint",
      "golines",
      "gofumpt",
      "goimports",
      "gopls",
      "gomodifytags",
      "gomodifytags",
      "htmlhint",
      "html-lsp",
      "jedi-language-server",
      "markdownlint-cli2",
      "markdown-toc",
      "mypy",
      "prettier",
      "revive",
      "ruff",
      "shfmt",
      "stylua",
      "svelte-language-server",
      "templ",
      "tree-sitter-cli",
      "typos",
      "typescript-language-server",
      "tailwindcss-language-server",
    },
  },
}
